#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

#push to private repo
#podman image load --input $HERE/$1.tar
#podman image tag localhost/$1:$OPEN5GS_VERSION localhost:5000/$1:$OPEN5GS_VERSION
#podman push localhost:5000/$1:$OPEN5GS_VERSION

#push to public quay repo
podman login
podman push localhost/$1:$OPEN5GS_VERSION quay.io/jnunez/$1:$OPEN5GS_VERSION