#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

docker image load --input $HERE/$1.tar
docker image tag localhost/$1:$OPEN5GS_VERSION localhost:5000/$1:$OPEN5GS_VERSION
docker push localhost:5000/$1:$OPEN5GS_VERSION
